unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded.."


# remove copy mode
unbind [

# binds
# leader key: C-Space
# leader + c: new-window
# leader + X: kill-window
# leader + x: kill-pane
# leader + !: break-pane (split pane into window)
# leader + ,: rename-window
# leader + m: swap-window
# leader + : : command-prompt (rename-window, rename-session, etc)
# leader + Space: change layout (default, even-horizontal, even-vertical, main-horizontal, main-vertical)
# leader + {: swap-pane -U
# leader + }: swap-pane -D

unbind [       # Enter copy mode
unbind ]       # Paste buffer
unbind q       # Show pane numbers


set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


# Split pane horizontally (same path)
unbind -       
bind-key v split-window -h -c "#{pane_current_path}"

# Split pane vertically (same path)
unbind |       
bind-key y split-window -v -c "#{pane_current_path}"

# Open new window in the same directory
bind c new-window -c "#{pane_current_path}"

unbind z
bind-key f resize-pane -Z

# Move windows left and right with Left and Right arrow keys
set-option -g renumber-windows on
unbind .
unbind m
bind-key m command-prompt -p "Swap with window:" "swap-window -d -t '%%'"

# move window to become a pane on a target window
unbind @
bind-key @ command-prompt -p "Join pane on window:" "join-pane -t '%%'"

unbind o
bind-key -r o display-popup -B -w 70% -h 50%  "~/bin/.local/scripts/tmux-sessionizer.sh"






# Resize panes with Vim-style capital keys
bind -r H resize-pane -L  # Resize pane left
bind -r J resize-pane -D  # Resize pane down
bind -r K resize-pane -U  # Resize pane up
bind -r L resize-pane -R  # Resize pane right

unbind x
bind x kill-pane 
bind-key X kill-window

set-option -g status-position top

set -g default-terminal "tmux-256color"



set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'catppuccin/tmux#v0.3.0'

# Theme settings
set -g @catppuccin_pane_status_enabled "no"
set -g @catppuccin_pane_border_status "off"
set -g @catppuccin_pane_border_style "fg=#{thm_gray}" # Use a value compatible with the standard tmux 'pane-border-style'
set -g @catppuccin_pane_active_border_style "fg=#{thm_blue}" # Use a value compatible with the standard tmux 'pane-border-active-style'
set -g @catppuccin_flavor 'mocha' # latte,frappe, macchiato or mocha
set -g @catppuccin_status_background "default" # none == default

set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory application session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_application_color "#F9E2AF"

# set -g @catppuccin_directory_text "#{pane_current_path}"
set -g @catppuccin_directory_text "#{s|^$HOME|~|:pane_current_path}"




run '~/.config/tmux/plugins/tpm/tpm'


